import { useEffect, useMemo, useState } from 'react'
import { App as AntApp, Avatar, Badge, Button, Card, Col, DatePicker, Descriptions, Drawer, Empty, Flex, Form, Input, Layout, List, Menu, Modal, Progress, Row, Segmented, Select, Space, Spin, Statistic, Table, Tabs, Tag, Timeline, Tooltip, Typography, Upload } from 'antd'
import { CalendarOutlined, CheckCircleOutlined, CloudSyncOutlined, DatabaseOutlined, EditOutlined, ExportOutlined, HeartOutlined, HomeOutlined, InboxOutlined, MessageOutlined, RadarChartOutlined, SafetyCertificateOutlined, SearchOutlined, SettingOutlined, UploadOutlined, WarningOutlined } from '@ant-design/icons'
import dayjs, { Dayjs } from 'dayjs'
import { API_BASE, api, EventItem, RankedEvent } from './api'

const { Header, Content, Sider } = Layout
const { Title, Text, Paragraph } = Typography

function fmt(value?:string){return value?dayjs(value).format('M月D日 HH:mm'):'待补充'}
function modeLabel(mode:string){return mode==='online'?'线上':mode==='hybrid'?'混合':'线下'}
function statusTag(status:string){const map:any={draft:['草稿','gold'],published:['已发布','green'],rejected:['已驳回','red'],expired:['已过期','default']};const item=map[status]||[status,'default'];return <Tag color={item[1]}>{item[0]}</Tag>}

function EventCard({event,onOpen,onRefresh}:{event:RankedEvent,onOpen:(e:RankedEvent)=>void,onRefresh:()=>void}){
  const {message}=AntApp.useApp()
  const favorite=async(e:any)=>{e.stopPropagation();try{await api.favorite(event.id);message.success('已收藏')}catch(err:any){message.error(err.message)}}
  return <Card className="event-card" hoverable onClick={()=>onOpen(event)}>
    <Flex justify="space-between" align="start" gap={12}><div><Tag color="cyan">{event.field_tags[0]||'综合'}</Tag><Tag>{modeLabel(event.location_mode)}</Tag></div><Text className="score">匹配 {Math.round(event.final_score*100)}</Text></Flex>
    <Title level={4}>{event.title}</Title>
    <Space direction="vertical" size={5} className="meta"><Text><CalendarOutlined/> {fmt(event.start_time)}</Text><Text><HomeOutlined/> {event.location||'待补充'}</Text><Text>{event.speaker||'主讲人待补充'}{event.speaker_affiliation?` · ${event.speaker_affiliation}`:''}</Text></Space>
    <div className="reason"><RadarChartOutlined/> {event.reason}</div>
    <Flex justify="space-between" align="center"><Text type="secondary">{event.organizer||event.source_site||'主办方待补充'}</Text><Space><Tooltip title="收藏"><Button type="text" shape="circle" icon={<HeartOutlined/>} onClick={favorite}/></Tooltip><Button type="link">查看详情</Button></Space></Flex>
  </Card>
}

function Explore(){
  const {message}=AntApp.useApp(); const [query,setQuery]=useState(''); const [field,setField]=useState<string>(); const [mode,setMode]=useState<string>(); const [dates,setDates]=useState<[Dayjs|null,Dayjs|null]|null>(null)
  const [events,setEvents]=useState<RankedEvent[]>([]); const [loading,setLoading]=useState(false); const [selected,setSelected]=useState<RankedEvent>(); const [chat,setChat]=useState(''); const [answer,setAnswer]=useState(''); const [chatLoading,setChatLoading]=useState(false)
  const search=async()=>{setLoading(true);try{const result=await api.search({query,field,location_mode:mode,date_from:dates?.[0]?.toISOString(),date_to:dates?.[1]?.endOf('day').toISOString(),page_size:24});setEvents(result.items)}catch(err:any){message.error(err.message)}finally{setLoading(false)}}
  useEffect(()=>{api.recommend().then(setEvents).catch((e)=>message.error(`加载失败：${e.message}`))},[])
  const ask=async()=>{if(!chat.trim())return;setChatLoading(true);try{const result=await api.chat(chat);setAnswer(result.answer);if(result.events.length)setEvents(result.events)}catch(err:any){message.error(err.message)}finally{setChatLoading(false)}}
  return <>
    <section className="hero-panel"><div><Text className="eyebrow">CAMPUS SEMINAR COPILOT</Text><Title>发现下一场值得参加的学术活动</Title><Paragraph>搜索已审核活动，查看可解释推荐，或直接用自然语言提问。</Paragraph></div><div className="health-pill"><span className="pulse"/> 无密钥本地模式</div></section>
    <Card className="search-panel"><Input.Search size="large" value={query} onChange={e=>setQuery(e.target.value)} onSearch={search} placeholder="搜索主题、主讲人或自然语言，例如：本周有哪些 AI 讲座？" enterButton={<><SearchOutlined/> 搜索</>}/>
      <Flex className="filters" gap={10} wrap><DatePicker.RangePicker value={dates} onChange={(v)=>setDates(v as any)} placeholder={['开始日期','结束日期']}/><Select allowClear placeholder="学科领域" value={field} onChange={setField} options={['人工智能','计算机','数学','生命科学','经济管理','人文社科','地球科学'].map(v=>({label:v,value:v}))}/><Select allowClear placeholder="活动形式" value={mode} onChange={setMode} options={[{label:'线下',value:'offline'},{label:'线上',value:'online'},{label:'混合',value:'hybrid'}]}/><Button onClick={()=>{setField(undefined);setMode(undefined);setDates(null);setQuery('')}}>清空</Button></Flex>
    </Card>
    <Card className="ask-panel"><Flex gap={12} align="center"><Avatar icon={<MessageOutlined/>}/><Input variant="borderless" value={chat} onChange={e=>setChat(e.target.value)} onPressEnter={ask} placeholder="问问活动助手：下周有哪些数学报告？"/><Button type="primary" loading={chatLoading} onClick={ask}>提问</Button></Flex>{answer&&<div className="answer"><Text strong>基于已发布活动的回答</Text><Paragraph>{answer}</Paragraph></div>}</Card>
    <Flex justify="space-between" align="end" className="section-title"><div><Text type="secondary">UPCOMING</Text><Title level={3}>即将举行</Title></div><Text type="secondary">{events.length} 场活动 · 评分分量可追溯</Text></Flex>
    <Spin spinning={loading}><Row gutter={[18,18]}>{events.map(event=><Col xs={24} md={12} xl={8} key={event.id}><EventCard event={event} onOpen={setSelected} onRefresh={search}/></Col>)}</Row>{!loading&&!events.length&&<Empty description="没有找到符合条件的已发布活动"/>}</Spin>
    <Drawer width={560} open={!!selected} onClose={()=>setSelected(undefined)} title="活动详情">{selected&&<><Space>{selected.field_tags.map(t=><Tag key={t} color="cyan">{t}</Tag>)}{statusTag(selected.status)}</Space><Title level={2}>{selected.title}</Title><Descriptions column={1} bordered size="small" items={[{key:'time',label:'时间',children:fmt(selected.start_time)},{key:'place',label:'地点',children:selected.location||'待补充'},{key:'speaker',label:'主讲人',children:selected.speaker||'待补充'},{key:'aff',label:'主讲人单位',children:selected.speaker_affiliation||'待补充'},{key:'org',label:'主办方',children:selected.organizer||'待补充'}]}/><Title level={5}>活动简介</Title><Paragraph>{selected.abstract||'待补充'}</Paragraph><Card size="small" className="score-breakdown"><Title level={5}>为什么推荐</Title><Paragraph>{selected.reason}</Paragraph><Row gutter={10}><Col span={8}><Statistic title="语义" value={Math.round(selected.semantic_score*100)} suffix="%"/></Col><Col span={8}><Statistic title="关键词" value={Math.round(selected.keyword_score*100)} suffix="%"/></Col><Col span={8}><Statistic title="时间" value={Math.round(selected.time_score*100)} suffix="%"/></Col></Row></Card><Flex gap={10} wrap><Button type="primary" icon={<HeartOutlined/>} onClick={()=>api.favorite(selected.id).then(()=>message.success('已收藏'))}>收藏</Button><Button icon={<CalendarOutlined/>} href={`${API_BASE}/api/events/${selected.id}.ics`}>导出日历</Button><Button icon={<ExportOutlined/>} href={selected.source_url} target="_blank" disabled={!selected.source_url}>查看来源</Button><Button onClick={()=>api.feedback(selected.id).then(()=>message.success('感谢反馈'))}>反馈有帮助</Button></Flex></>}</Drawer>
  </>
}

function Ingest(){
  const {message}=AntApp.useApp();const [text,setText]=useState('');const [draft,setDraft]=useState<EventItem>();const [loading,setLoading]=useState(false)
  const parse=async()=>{setLoading(true);try{setDraft(await api.parseText(text));message.success('已生成待审核草稿')}catch(e:any){message.error(e.message)}finally{setLoading(false)}}
  return <><div className="page-heading"><div><Text type="secondary">INGEST</Text><Title level={2}>上传与字段解析</Title><Paragraph>支持粘贴通知、PDF、图片和文本。缺失字段保持“待补充”，不会猜测。</Paragraph></div></div><Row gutter={[18,18]}><Col xs={24} lg={14}><Card title="粘贴活动通知"><Input.TextArea rows={13} value={text} onChange={e=>setText(e.target.value)} placeholder={'报告题目：……\n报告人：……\n报告时间：……\n报告地点：……'}/><Button type="primary" icon={<RadarChartOutlined/>} loading={loading} disabled={text.length<5} onClick={parse} className="top-gap">解析为草稿</Button></Card></Col><Col xs={24} lg={10}><Upload.Dragger showUploadList={false} beforeUpload={async file=>{try{setDraft(await api.upload(file));message.success('文件已解析为草稿')}catch(e:any){message.error(e.message)}return false}}><p className="ant-upload-drag-icon"><InboxOutlined/></p><p>拖放 PDF、图片、TXT 或 Markdown</p><Text type="secondary">最大 10 MB；无 OCR 时图片进入待补充草稿</Text></Upload.Dragger>{draft&&<Card className="top-gap" title="解析结果" extra={statusTag(draft.status)}><Descriptions size="small" column={1} items={[{key:'t',label:'标题',children:draft.title},{key:'s',label:'主讲人',children:draft.speaker||'待补充'},{key:'d',label:'时间',children:fmt(draft.start_time)},{key:'l',label:'地点',children:draft.location||'待补充'}]}/><Progress percent={Math.round(draft.extraction_confidence*100)} size="small"/><Text type="secondary">解析置信度</Text></Card>}</Col></Row></>
}

function Admin(){
  const {message}=AntApp.useApp();const [items,setItems]=useState<EventItem[]>([]);const [loading,setLoading]=useState(false);const [editing,setEditing]=useState<EventItem>();const [form]=Form.useForm()
  const load=async()=>{setLoading(true);try{setItems(await api.adminEvents())}catch(e:any){message.error(e.message)}finally{setLoading(false)}};useEffect(()=>{load()},[])
  const review=async(id:number,action:'publish'|'reject')=>{try{await api.review(id,action);message.success(action==='publish'?'已发布并同步索引':'已驳回');load()}catch(e:any){message.error(e.message)}}
  const edit=(item:EventItem)=>{setEditing(item);form.setFieldsValue({...item,start_time:item.start_time?dayjs(item.start_time):null,field_tags:item.field_tags})}
  const save=async()=>{const values=await form.validateFields();try{await api.updateEvent(editing!.id,{...values,start_time:values.start_time?.toISOString()});message.success('字段已保存');setEditing(undefined);load()}catch(e:any){message.error(e.message)}}
  const columns:any[]=[{title:'活动',dataIndex:'title',render:(v:string,r:EventItem)=><div><Text strong>{v}</Text><br/><Text type="secondary">{fmt(r.start_time)} · {r.organizer||'主办方待补充'}</Text></div>},{title:'状态',dataIndex:'status',width:90,render:statusTag},{title:'质量',dataIndex:'quality_score',width:90,render:(v:number)=><Progress type="circle" size={42} percent={Math.round(v*100)}/>},{title:'操作',width:260,render:(_:any,r:EventItem)=><Space wrap><Button size="small" icon={<EditOutlined/>} onClick={()=>edit(r)}>编辑</Button><Button size="small" type="primary" disabled={r.status==='published'} onClick={()=>review(r.id,'publish')}>发布</Button><Button size="small" danger onClick={()=>review(r.id,'reject')}>驳回</Button></Space>}]
  return <><div className="page-heading"><div><Text type="secondary">REVIEW</Text><Title level={2}>管理后台</Title><Paragraph>审核抽取证据与字段完整度，编辑后发布到检索索引。</Paragraph></div><Button icon={<CloudSyncOutlined/>} onClick={load}>刷新</Button></div><Card><Tabs items={[{key:'all',label:`全部 ${items.length}`,children:<Table rowKey="id" loading={loading} columns={columns} dataSource={items} pagination={{pageSize:8}}/>},{key:'draft',label:`待审核 ${items.filter(i=>i.status==='draft').length}`,children:<Table rowKey="id" columns={columns} dataSource={items.filter(i=>i.status==='draft')} pagination={false}/>} ]}/></Card><Modal open={!!editing} title="编辑活动字段" onCancel={()=>setEditing(undefined)} onOk={save} width={680}><Form form={form} layout="vertical"><Form.Item name="title" label="标题" rules={[{required:true}]}><Input/></Form.Item><Row gutter={12}><Col span={12}><Form.Item name="speaker" label="主讲人"><Input placeholder="待补充"/></Form.Item></Col><Col span={12}><Form.Item name="speaker_affiliation" label="主讲人单位"><Input/></Form.Item></Col></Row><Row gutter={12}><Col span={12}><Form.Item name="start_time" label="开始时间"><DatePicker showTime style={{width:'100%'}}/></Form.Item></Col><Col span={12}><Form.Item name="location" label="地点"><Input placeholder="待补充"/></Form.Item></Col></Row><Form.Item name="organizer" label="主办方"><Input/></Form.Item><Form.Item name="field_tags" label="领域标签"><Select mode="tags"/></Form.Item><Form.Item name="abstract" label="摘要"><Input.TextArea rows={5}/></Form.Item></Form></Modal></>
}

function Crawl(){
  const {message}=AntApp.useApp();const [sources,setSources]=useState<any[]>([]);const [runs,setRuns]=useState<any[]>([]);const [busy,setBusy]=useState(false)
  const load=()=>Promise.all([api.sources(),api.runs()]).then(([s,r])=>{setSources(s);setRuns(r)}).catch(e=>message.error(e.message));useEffect(()=>{load()},[])
  const run=async(mode:'fixture'|'live')=>{setBusy(true);try{const result=await api.crawl(mode);const failed=result.runs.filter((r:any)=>r.status==='failed').length;message[failed?'warning':'success'](failed?`${failed} 个站点失败，其余已继续`:'定时增量同步完成');load()}catch(e:any){message.error(e.message)}finally{setBusy(false)}}
  return <><div className="page-heading"><div><Text type="secondary">SCHEDULED SYNC</Text><Title level={2}>采集状态</Title><Paragraph>五个独立站点适配器；单站失败隔离。生产文档称为“定时增量同步”，不宣称实时推送。</Paragraph></div><Space><Button onClick={()=>run('fixture')} loading={busy}>运行本地 Fixture</Button><Button type="primary" icon={<CloudSyncOutlined/>} onClick={()=>run('live')} loading={busy}>运行在线同步</Button></Space></div><Row gutter={[16,16]}>{sources.map(source=><Col xs={24} md={12} xl={8} key={source.id}><Card><Flex justify="space-between"><Avatar icon={<DatabaseOutlined/>}/><Badge status={source.enabled?'success':'default'} text={source.enabled?'启用':'停用'}/></Flex><Title level={4}>{source.name}</Title><Text type="secondary">{source.base_url}</Text><br/><Tag className="top-gap">{source.adapter}</Tag></Card></Col>)}</Row><Card title="最近运行记录" className="top-gap"><Timeline items={runs.map(run=>({color:run.status==='success'?'green':'red',children:<><Text strong>{run.status==='success'?'同步成功':'同步失败'}</Text><br/><Text type="secondary">{fmt(run.started_at)} · 发现 {run.items_seen} · 新增 {run.items_created} · 重复 {run.items_duplicate}{run.error_message?` · ${run.error_message}`:''}</Text></>}))}/>{!runs.length&&<Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="暂无运行记录"/>}</Card></>
}

function BadCases(){
  const {message}=AntApp.useApp();const [items,setItems]=useState<any[]>([]);const load=()=>api.badCases().then(setItems).catch(e=>message.error(e.message));useEffect(()=>{load()},[])
  return <><div className="page-heading"><div><Text type="secondary">QUALITY LOOP</Text><Title level={2}>坏案例管理</Title><Paragraph>集中处理无结果问答、错误推荐和用户负反馈。</Paragraph></div></div><Card><List dataSource={items} locale={{emptyText:'暂无坏案例'}} renderItem={item=><List.Item actions={[item.status==='open'?<Button size="small" type="primary" onClick={()=>api.resolveCase(item.id).then(()=>{message.success('已标记解决');load()})}>标记解决</Button>:statusTag(item.status)]}><List.Item.Meta avatar={<Avatar className="bad-avatar" icon={<WarningOutlined/>}/>} title={<Space><Text strong>{item.query}</Text><Tag>{item.error_type}</Tag></Space>} description={item.expected_result||item.wrong_result||'由系统自动记录，等待补充预期结果'}/></List.Item>}/></Card></>
}

const nav=[{key:'explore',icon:<RadarChartOutlined/>,label:'活动探索'},{key:'ingest',icon:<UploadOutlined/>,label:'上传解析'},{key:'admin',icon:<SafetyCertificateOutlined/>,label:'管理后台'},{key:'crawl',icon:<CloudSyncOutlined/>,label:'采集状态'},{key:'bad',icon:<WarningOutlined/>,label:'坏案例'}]

function Shell(){
  const [page,setPage]=useState('explore');const [collapsed,setCollapsed]=useState(false);const content=useMemo(()=>({explore:<Explore/>,ingest:<Ingest/>,admin:<Admin/>,crawl:<Crawl/>,bad:<BadCases/>}[page]),[page])
  return <Layout className="app-shell"><Sider collapsible breakpoint="lg" collapsedWidth="0" collapsed={collapsed} onCollapse={setCollapsed} className="sidebar" width={238}><div className="brand"><div className="brand-mark"><RadarChartOutlined/></div><div><Text>珞珈学术雷达</Text><small>SEMINAR COPILOT</small></div></div><Menu mode="inline" selectedKeys={[page]} items={nav} onClick={({key})=>{setPage(key);if(window.innerWidth<992)setCollapsed(true)}}/><div className="sidebar-foot"><CheckCircleOutlined/> SQLite 降级模式可用</div></Sider><Layout><Header className="topbar"><div><Text type="secondary">武汉大学学术活动聚合与问答</Text></div><Space><Badge status="success" text="服务就绪"/><Avatar>访</Avatar></Space></Header><Content className="content">{content}</Content></Layout></Layout>
}

export default function App(){return <AntApp><Shell/></AntApp>}
